# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/ankivalenz',
                'doc_host': 'https://vangberg.github.io',
                'git_url': 'https://github.com/vangberg/ankivalenz',
                'lib_path': 'ankivalenz'},
  'syms': {'ankivalenz.core': {'ankivalenz.core.foo': ('core.html#foo', 'ankivalenz/core.py')}}}