# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/ankivalenz.ipynb.

# %% auto 0
__all__ = ['foo', 'say_hi']

# %% ../nbs/ankivalenz.ipynb 3
def foo(): pass

# %% ../nbs/ankivalenz.ipynb 4
def say_hi(to):
    "Say hi to someone"
    return f'Hi {to}'
