# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/types.ipynb.

# %% auto 0
__all__ = ['PathNode', 'BasicNode', 'StandaloneNode', 'ClozeNode', 'Node', 'Card', 'Path', 'Delimeter', 'BasicCard', 'ClozeCard']

# %% ../nbs/types.ipynb 1
from dataclasses import dataclass, field
from typing import Tuple, Union

# %% ../nbs/types.ipynb 3
@dataclass
class Delimeter:
    contents: str

# %% ../nbs/types.ipynb 5
PathNode = Tuple[str, list["Node"]]
BasicNode = Tuple[str, Delimeter, str]
StandaloneNode = Tuple[Delimeter, str]
ClozeNode = str

Node = Union[list["Node"], PathNode, BasicNode, StandaloneNode, ClozeNode]

# %% ../nbs/types.ipynb 7
@dataclass(order=True)
class BasicCard:
    question: str
    answer: str
    path: list[str]
    reverse: bool = False


@dataclass(order=True)
class ClozeCard:
    question: str
    path: list[str]


Card = Union[BasicCard, ClozeCard]

Path = list[str]
